name: Deploy Blog 
on:
        push:
                branches:
                        - Blog

jobs:
        build-and-deploy:
                runs-on: ubuntu-latest
                steps:

                        - name: Check Out
                          uses: actions/checkout@v2

                        - name: install hexo

                          run: |
                                  npm config set registry https://registry.npm.taobao.org
                                  npm install hexo-cli -g
                                  npm install hexo --no-optional
     

                        - name: hexo generate public

                          run: |
                                  hexo clean
                                  hexo g
                      
                        - name: Deploy
                          uses: easingthemes/ssh-deploy@v2.2.11 
                          env:
                           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                           ARGS: "-rltgoDzvO"
                           SOURCE: ${{ secrets.SOURCE }}
                           REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                           REMOTE_USER: ${{ secrets.REMOTE_USER }}
                           REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
                           TARGET: ${{ secrets.TARGET }}
